[build]
  functions = "netlify/functions"
  base = "/"
  command = "vite build"
  publish = "dist"

[functions."cleanUp"]
  schedule = "@daily"

[[redirects]]
  from = "/api/get"
  to = "/.netlify/functions/get"
  status = 200

[[redirects]]
  from = "/api/post"
  to = "/.netlify/functions/post"
  status = 200