[build]
  functions = "netlify/functions"

[functions."cleanUp"]
  schedule = "@daily"

[[headers]]
  for = "/*" 
  [headers.values]
    access-control-allow-origin = "*"

[[redirects]]
  from = "/api/get"
  to = "/.netlify/functions/get"
  status = 200
  headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
  from = "/api/post"
  to = "/.netlify/functions/post"
  status = 200
  headers = { Access-Control-Allow-Origin = "*" }