[build]
  functions = "netlify/functions"

[functions."cleanUp"]
  schedule = "@daily"

[[redirects]]
  from = "/api/get"
  to = "/.netlify/functions/get"
  status = 200
  headers = { Access-Control-Allow-Origin = "*" }

[[redirects]]
  from = "/api/post"
  to = "/.netlify/functions/post"
  status = 200
  headers = { Access-Control-Allow-Origin = "*" }