export const POSTGRESQL_DATABASE_NAME = "events";
export const POSTGRESQL_KEY_EVENT_NAME = "event_name";
export const POSTGRESQL_KEY_TIMESTAMP_NAME = "timestamp";

export const GET_QUERY = `SELECT ${POSTGRESQL_KEY_EVENT_NAME}, ${POSTGRESQL_KEY_TIMESTAMP_NAME}
FROM ${POSTGRESQL_DATABASE_NAME}
WHERE ${POSTGRESQL_KEY_TIMESTAMP_NAME} >= $1`;
